### ISSUE TITLE
Error in Opencart Module 2.0.5

### ISSUE THREAD

**Issue by lenoirmind** [ICEPAYdev/OpenCart#1]
One of my clients pointed out, that she get errors in a dialog box when she'd advanced into the payment stage. Bit of research got me the following error message:

Internal Server Error
Internal Server Error
<b>Warning</b>: require_once(/home/sites/site36954/cms/shop/catalog/model/payment/icepay/src/icepay_api_webservice.php) [<a href='function.require-once'>function.require-once</a>]: failed to open stream: No such file or directory in <b>/home/sites/site36954/cms/shop/catalog/model/payment/icepay_basic.php</b> on line <b>11</b>

I've checked the archive structure op de opencast module on saw that "icepay_api_webservice.php" is not in the /src/ subfolder. Copying the three files that reside in "/catalog/model/payment/icepay/" into "/catalog/model/payment/icepay/src" solved the error message and payment can be successfully processed.

Could this folder be checked in the archive.

Kind regards,

Roger

**Comment by tsygankov** [comment]
Dear Roger,

Thank you for your feedback! We've fixed that issue and released a new version of ICEPAY module for Opencart.

Issue fixed in v2.0.6
